name: Cache Dependencies

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-22cc6ff-${{ runner.os }}
          restore-keys: |
            cache-22cc6ff-

      - name: prime-cache-22cc6ff
        run: echo "Cache hit: ${{ steps.cache.outputs.cache-hit }}"
