name: Email Step Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # allows manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 23f1001647@ds.study.iitm.ac.in
        run: echo "Hello, world!"
